""" код для двух последних картинок в readme.md, ничего интересного"""

sinn = generate_sin(t, sampling_rate, 50)
sinn_decimated = decimator(sinn)
sinn_interpolated = interpolator(t_decimated, sinn_decimated, t)
plt.figure(2)
plt.subplot(3, 1, 1)
plt.title("Синус 50 Гц")
plt.plot(t, sinn, color = "blue", label = "generated", marker = ".")
plt.grid(True)
plt.subplot(3, 1, 2)
plt.plot(t, sinn, color = "blue", label = "generated", marker = ".")
plt.plot(t_decimated, sinn_decimated, color = "red", label = "decimated", marker = ".")
plt.grid(True)
plt.subplot(3, 1, 3)
plt.plot(t, sinn, color = "blue", label = "generated", marker = ".")
plt.plot(t_decimated, sinn_decimated, color = "red", label = "decimated", marker = ".")
plt.plot(t, sinn_interpolated, color = "green", label = "interpolated", marker = ".")
plt.legend()
plt.grid(True)
